name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run:  git ls-files *.{c,h} | xargs clang-format -i --verbose src/Convert/main.c src/LibConvert/coursework.c src/libhello/coursework.h

      - name: Build application
        run: make
    
      - name: Build test
        run: make test

      - name: Build runtest
        run: make run_test
