name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose && diff -u <(git cat-file -p HEAD:file.c) <(cat file.c)

      - name: Build application
        run: make
